name: Development

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_dispatch:


jobs:
  lint:
    name: Analyzer
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Get flutter from stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Setup flutter env
        run: flutter pub get
        working-directory: ./braille_abc
      
      - name: Run static analyzer
        run: flutter analyze
        working-directory: ./braille_abc


  build_ios:
    name: IOS build
    runs-on: macos-latest
    needs: [lint]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Get flutter from stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Setup flutter env
        run: flutter pub get
        working-directory: ./braille_abc
      
      - name: Build
        run: flutter build ios --release --no-codesign --no-tree-shake-icons
        working-directory: ./braille_abc


  build_android:
    name: Android build
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Get flutter from stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Get java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Setup flutter env
        run: flutter pub get
        working-directory: ./braille_abc
      
      - name: Setup signing key and key.properties
        run: |
          echo "" > braille_abc/android/upload-keystore.jks
          echo "storePassword=
          keyPassword=
          keyAlias=upload
          storeFile=$(pwd)/braille_abc/android/upload-keystore.jks" > braille_abc/android/key.properties
        
      - name: Build
        run: flutter build appbundle --no-tree-shake-icons
        working-directory: ./braille_abc


  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build_android, build_ios]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Get flutter from stable
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Setup flutter env
        run: flutter pub get
        working-directory: ./braille_abc
      
      - name: Test
        run: flutter test
        working-directory: ./braille_abc
