name: Development

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_dispatch:


jobs:
  lint:
    name: Analyze source code
    runs-on: ubuntu-latest

    steps:
     # Git checkout with lfs caching
      - uses: actions/checkout@v2
        with:
          lfs: true 
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      # Setup flutter from stable
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Setup env and run analyzer
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter analyze
        working-directory: ./braille_abc


  build_ios:
    name: Build IOS
    runs-on: macos-latest
    needs: [lint]

    steps:
      # Git checkout with lfs caching
      - uses: actions/checkout@v2
        with:
          lfs: true 
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      # Setup flutter from stable
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      # Setup env and build
      - run: git lfs pull
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter build ios --release --no-codesign --no-tree-shake-icons
        working-directory: ./braille_abc


  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      # Git checkout with lfs caching
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
          
      # Setup flutter from stable and java 11
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      # Setup env and build
      - run: git lfs pull
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter build appbundle --no-tree-shake-icons
        working-directory: ./braille_abc


  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [build_android, build_ios]

    steps:
      # Git checkout with lfs caching
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
          
      # Setup flutter from stable
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Setup env and test
      - run: git lfs pull
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter test
        working-directory: ./braille_abc
