name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run flutter analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter analyze
        working-directory: ./braille_abc


  build_ios:
    name: Build with Flutter for IOS
    runs-on: macos-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true 
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - run: git lfs pull
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter build ios --no-codesign --no-tree-shake-icons
        working-directory: ./braille_abc

      - run: ls braille_abc/build
      - run: ls braille_abc/build/ios
      - run: ls braille_abc/build/ios/outputs
      - run: ls braille_abc/build/ios/outputs/ipa
      - run: ls braille_abc/build/ios/outputs/ipa/release

      - uses: actions/upload-artifact@v1
        with:
          name: build-ipa
          path: braille_abc/build/app/outputs/ipa/release/app-release.ipa


  build_android:
    name: Build with Flutter for Android
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true 
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - run: git lfs pull
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter build apk --no-tree-shake-icons
        working-directory: ./braille_abc
      
      - uses: actions/upload-artifact@v1
        with:
          name: build-apk
          path: braille_abc/build/app/outputs/apk/release/app-release.apk
