name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Run flutter analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter analyze
        working-directory: ./braille_abc

  build_ios:
    name: Build with Flutter for IOS
    runs-on: macos-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter build ios --no-codesign
        working-directory: ./braille_abc
