name: CI

on: [push, pull_request]
working-directory: ./braille_abc

jobs:
  lint:
    name: Run flutter analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter analyze

  build_ios:
    name: Build with Flutter for IOS
    runs_on: macos-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build ios --no-codesign
