name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Analyze source code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter analyze
        working-directory: ./braille_abc


  build_ios:
    name: Build IOS
    runs-on: macos-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true 
      
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - run: git lfs pull
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter build ios --release --no-codesign --no-tree-shake-icons
        working-directory: ./braille_abc


  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
          
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - run: git lfs pull
      - run: flutter pub get
        working-directory: ./braille_abc
      - run: flutter build apk --release --no-tree-shake-icons
        working-directory: ./braille_abc
      
      - uses: actions/upload-artifact@v1
        with:
          name: build-apk
          path: braille_abc/build/app/outputs/apk/release/app-release.apk
