name: Release

on:
  push:
    tags:
      - 'v*.*'


jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get current tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create empty release GitHub page
        uses: softprops/action-gh-release@v1
        with:
          name: Learn Braille IOS ${{ env.RELEASE_VERSION }}
          files: |
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
