name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get tag name
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - uses: softprops/action-gh-release@v1
        with:
          body_path: docs/release/$RELEASE_VERSION/CHANGELOG.md
          files: |
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
